# Generated by Django 5.1.3 on 2024-11-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
